# Dockerfile

FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --omit=dev

# Copy application files
COPY . .

# Accept build-time arguments (from GitHub Actions)
# Firebase Keys
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Google Cloud Keys
ARG NEXT_PUBLIC_GOOGLE_PRIVATE_KEY
ARG NEXT_PUBLIC_GOOGLE_PRIVATE_KEY_ID
ARG NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_AUTH_URI
ARG NEXT_PUBLIC_GOOGLE_TOKEN_URI
ARG NEXT_PUBLIC_GOOGLE_AUTH_PROVIDER_CERT_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_CERT_URL
ARG NEXT_PUBLIC_GOOGLE_BUCKET_NAME
ARG NEXT_PUBLIC_GOOGLE_SERVICE_ACCOUNT_TYPE

# GROQ Key
ARG NEXT_PUBLIC_GROQ_API_KEY

# Expose them to the build environment (so Next.js can use them)
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

ENV NEXT_PUBLIC_GOOGLE_PRIVATE_KEY=$NEXT_PUBLIC_GOOGLE_PRIVATE_KEY
ENV NEXT_PUBLIC_GOOGLE_PRIVATE_KEY_ID=$NEXT_PUBLIC_GOOGLE_PRIVATE_KEY_ID
ENV NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL=$NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_GOOGLE_AUTH_URI=$NEXT_PUBLIC_GOOGLE_AUTH_URI
ENV NEXT_PUBLIC_GOOGLE_TOKEN_URI=$NEXT_PUBLIC_GOOGLE_TOKEN_URI
ENV NEXT_PUBLIC_GOOGLE_AUTH_PROVIDER_CERT_URL=$NEXT_PUBLIC_GOOGLE_AUTH_PROVIDER_CERT_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_CERT_URL=$NEXT_PUBLIC_GOOGLE_CLIENT_CERT_URL
ENV NEXT_PUBLIC_GOOGLE_BUCKET_NAME=$NEXT_PUBLIC_GOOGLE_BUCKET_NAME
ENV NEXT_PUBLIC_GOOGLE_SERVICE_ACCOUNT_TYPE=$NEXT_PUBLIC_GOOGLE_SERVICE_ACCOUNT_TYPE

ENV NEXT_PUBLIC_GROQ_API_KEY=$NEXT_PUBLIC_GROQ_API_KEY


ENV NODE_ENV=production


RUN npm install --omit=dev

# Build the application
RUN npm run build

# Expose port for Cloud Run
EXPOSE 8080

# Start server
CMD ["npm", "start"]
